#Ce fichier contiens la config de base du serveur---
Install: false
General:
    name: computercraft_api
DataBase:
    dbAdress: 192.168.2.52
    dbName: snapmaker
    dbUser: snapmaker
    dbPassword: snapmaker
    dbPort: 3306